#ifndef SIM800_AT_API_HPP
#define SIM800_AT_API_HPP

// -----------------------------------------------------------------------
// GENERATED FILE - DO NOT EDIT
// Generated by tools/generate.py from data/*.yaml
// -----------------------------------------------------------------------

#include "at_types.hpp"
#include "at_commands.hpp"
#include "urcs.hpp"
#include <cstddef>
#include <cstdint>

namespace sim800_at {

inline constexpr const char* MODULE_NAMES[] = {
    "SIM800L",
    "SIM800C",
    "SIM808",
    "SIM868",
    "SIM800A",
    "SIM800F",
    "SIM800H",
    "SIM800",
    "SIM800C-DS",
};

inline constexpr const char* CATEGORY_LABELS[] = {
    "V.25TER",
    "3GPP TS 27.007",
    "3GPP TS 27.005",
    "SIM Application Toolkit",
    "SIMCom Special",
    "GPRS Support",
    "TCPIP Application Toolkit",
    "IP Application",
    "PING Support",
    "HTTP Application",
    "FTP Application",
    "GSM Location Application",
    "Email Application",
    "MMS Application",
    "DDET Application",
    "RECORD Application",
    "TTS Application",
};

inline constexpr const char* CATEGORY_IDS[] = {
    "V25TER",
    "3GPP_27007",
    "3GPP_27005",
    "STK",
    "SIMCom",
    "GPRS",
    "TCPIP",
    "IP",
    "PING",
    "HTTP",
    "FTP",
    "GSM_Location",
    "Email",
    "MMS",
    "DDET",
    "RECORD",
    "TTS",
};

inline constexpr std::size_t MODULE_COUNT = 9;
inline constexpr std::size_t CATEGORY_COUNT = 17;

inline char lower_ascii(char c) noexcept {
    return (c >= 'A' && c <= 'Z') ? static_cast<char>(c + 32) : c;
}

inline bool str_equal_cs(const char* a, const char* b) noexcept {
    if (a == nullptr || b == nullptr) return false;
    while (*a != '\0' && *b != '\0') {
        if (*a != *b) return false;
        ++a; ++b;
    }
    return *a == *b;
}

inline bool str_equal_ci(const char* a, const char* b) noexcept {
    if (a == nullptr || b == nullptr) return false;
    while (*a != '\0' && *b != '\0') {
        if (lower_ascii(*a) != lower_ascii(*b)) return false;
        ++a; ++b;
    }
    return *a == *b;
}

inline std::size_t total_modules() noexcept { return MODULE_COUNT; }
inline std::size_t total_categories() noexcept { return CATEGORY_COUNT; }
inline std::size_t total_commands() noexcept { return AT_COMMAND_COUNT; }
inline std::size_t total_urcs() noexcept { return URC_COUNT; }

inline const char* module_name_at(std::size_t index) noexcept {
    if (index >= MODULE_COUNT) return nullptr;
    return MODULE_NAMES[index];
}

inline int module_index(const char* name) noexcept {
    if (name == nullptr) return -1;
    for (std::size_t i = 0; i < MODULE_COUNT; ++i) {
        if (str_equal_cs(MODULE_NAMES[i], name)) return static_cast<int>(i);
    }
    return -1;
}

inline Category category_from_id(const char* id) noexcept {
    if (id == nullptr) return Category::INVALID;
    for (std::size_t i = 0; i < CATEGORY_COUNT; ++i) {
        if (str_equal_ci(CATEGORY_IDS[i], id)) {
            return static_cast<Category>(i);
        }
    }
    return Category::INVALID;
}

inline const char* category_name(Category c) noexcept {
    if (c == Category::INVALID) return "<invalid>";
    if (c == Category::COUNT) return "<count>";
    std::size_t idx = static_cast<std::size_t>(c);
    if (idx >= CATEGORY_COUNT) return "<invalid>";
    return CATEGORY_LABELS[idx];
}

inline const ATCommand* find_command(const char* name) noexcept {
    if (name == nullptr) return nullptr;
    for (std::size_t i = 0; i < AT_COMMAND_COUNT; ++i) {
        if (str_equal_ci(AT_COMMANDS[i].name, name)) return &AT_COMMANDS[i];
    }
    return nullptr;
}

inline const URC* find_urc(const char* name) noexcept {
    if (name == nullptr) return nullptr;
    for (std::size_t i = 0; i < URC_COUNT; ++i) {
        if (str_equal_cs(URCS[i].name, name)) return &URCS[i];
    }
    return nullptr;
}

inline bool is_command_supported(const ATCommand* cmd,
                                 const char* module_name) noexcept {
    if (cmd == nullptr || module_name == nullptr) return false;
    int idx = module_index(module_name);
    if (idx < 0) return false;
    return cmd->module_support[idx];
}

inline bool is_urc_supported(const URC* urc,
                             const char* module_name) noexcept {
    if (urc == nullptr || module_name == nullptr) return false;
    int idx = module_index(module_name);
    if (idx < 0) return false;
    return urc->module_support[idx];
}

inline const ATCommand* commands_by_category(Category c,
                                             std::size_t& count) noexcept {
    count = 0;
    if (c == Category::INVALID || c == Category::COUNT) return nullptr;
    std::size_t idx = static_cast<std::size_t>(c);
    if (idx >= CATEGORY_COUNT) return nullptr;
    count = CMDS_BY_CAT_TABLE[idx].count;
    return CMDS_BY_CAT_TABLE[idx].data;
}

inline const URC* urcs_by_category(Category c,
                                   std::size_t& count) noexcept {
    count = 0;
    if (c == Category::INVALID || c == Category::COUNT) return nullptr;
    std::size_t idx = static_cast<std::size_t>(c);
    if (idx >= CATEGORY_COUNT) return nullptr;
    count = URCS_BY_CAT_TABLE[idx].count;
    return URCS_BY_CAT_TABLE[idx].data;
}

inline const ATCommand* commands_for_module(const char* module_name,
                                            std::size_t& count) noexcept {
    count = 0;
    if (module_name == nullptr) return nullptr;
    int idx = module_index(module_name);
    if (idx < 0) return nullptr;
    count = CMDS_BY_MOD_TABLE[idx].count;
    return CMDS_BY_MOD_TABLE[idx].data;
}

inline const URC* urcs_for_module(const char* module_name,
                                  std::size_t& count) noexcept {
    count = 0;
    if (module_name == nullptr) return nullptr;
    int idx = module_index(module_name);
    if (idx < 0) return nullptr;
    count = URCS_BY_MOD_TABLE[idx].count;
    return URCS_BY_MOD_TABLE[idx].data;
}

} // namespace sim800_at

#endif // SIM800_AT_API_HPP
