#ifndef SIM800_AT_TYPES_HPP
#define SIM800_AT_TYPES_HPP

// -----------------------------------------------------------------------
// GENERATED FILE - DO NOT EDIT
// Generated by tools/generate.py from data/*.yaml
// -----------------------------------------------------------------------

#include <cstdint>
#include <cstddef>

namespace sim800_at {

enum class Category : std::uint8_t {
    V25TER = 0,
    cat_3GPP_27007 = 1,
    cat_3GPP_27005 = 2,
    STK = 3,
    SIMCom = 4,
    GPRS = 5,
    TCPIP = 6,
    IP = 7,
    PING = 8,
    HTTP = 9,
    FTP = 10,
    GSM_Location = 11,
    Email = 12,
    MMS = 13,
    DDET = 14,
    RECORD = 15,
    TTS = 16,
    COUNT = 17,
    INVALID = 0xFF
};

enum class ParamType : std::uint8_t {
    String = 0,
    Int = 1,
    Bool = 2,
    Enum = 3,
    COUNT = 4
};

struct Parameter {
    const char* name;
    ParamType   type;
    const char* values_or_range;
};

struct ATCommand {
    const char*        name;
    Category           category;
    const char*        description;
    const Parameter*   parameters;
    std::size_t        parameter_count;
    const char* const* responses;
    std::size_t        response_count;
    const char* const* related_urcs;
    std::size_t        related_urc_count;
    const bool*        module_support;
    const char*        manual_ref;
};

struct URC {
    const char*        name;
    Category           category;
    const char*        description;
    const char* const* payload;
    std::size_t        payload_count;
    const char* const* enabled_by;
    std::size_t        enabled_by_count;
    const bool*        module_support;
    const char*        manual_ref;
};

} // namespace sim800_at

#endif // SIM800_AT_TYPES_HPP
