#ifndef SIM800_AT_HPP
#define SIM800_AT_HPP

// ---------------------------------------------------------------------------
// SIMCom SIM800 Series - AT Command & URC Database
//
// This is the umbrella header. Include only this header in user code.
//
// The three layers below are generated by tools/generate.py from the YAML
// sources under data/. Do not edit them by hand.
//
// Requirements:
//   - C++17 (inline constexpr)
//   - No dynamic allocation
//   - No Arduino-specific dependencies
// ---------------------------------------------------------------------------

#include "at_types.hpp"
#include "at_commands.hpp"
#include "urcs.hpp"
#include "at_api.hpp"

#endif // SIM800_AT_HPP
