#ifndef SIM800_AT_URCS_HPP
#define SIM800_AT_URCS_HPP

// -----------------------------------------------------------------------
// GENERATED FILE - DO NOT EDIT
// Generated by tools/generate.py from data/*.yaml
// -----------------------------------------------------------------------

#include "at_types.hpp"
#include <cstddef>

namespace sim800_at {

inline constexpr bool URCS_SUPPORT_0[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_1[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_2[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_3[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_4[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_5[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_6[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_7[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_8[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_9[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_10[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_11[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_12[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_13[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_14[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_15[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_16[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_17[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_18[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_19[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_20[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_21[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_22[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_23[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_24[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_25[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_26[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_27[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_28[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_29[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_30[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_31[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_32[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_33[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_34[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_35[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_36[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_37[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_38[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_39[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_40[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_41[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_42[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_43[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_44[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_45[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_46[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_47[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_48[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_49[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_50[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_51[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_52[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_53[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_54[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_55[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_56[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_57[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_58[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_59[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_60[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_61[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_62[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_63[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_64[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_65[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_66[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_67[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_68[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_69[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_70[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_71[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_72[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_73[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_74[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_75[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_76[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_77[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_78[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_79[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_80[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_81[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_82[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_83[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_84[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_85[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_86[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_87[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_88[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_89[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_90[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_91[] = { true, false, true, false, true, true, true, true, false };
inline constexpr bool URCS_SUPPORT_92[] = { true, true, true, true, true, true, true, true, false };
inline constexpr bool URCS_SUPPORT_93[] = { true, true, true, true, true, true, true, true, true };
inline constexpr bool URCS_SUPPORT_94[] = { true, true, true, true, true, true, true, true, true };

inline constexpr const char** URCS_PAYLOAD_0 = nullptr;
inline constexpr const char** URCS_PAYLOAD_1 = nullptr;
inline constexpr const char** URCS_PAYLOAD_2 = nullptr;
inline constexpr const char** URCS_PAYLOAD_3 = nullptr;
inline constexpr const char** URCS_PAYLOAD_4 = nullptr;
inline constexpr const char** URCS_PAYLOAD_5 = nullptr;
inline constexpr const char** URCS_PAYLOAD_6 = nullptr;
inline constexpr const char** URCS_PAYLOAD_7 = nullptr;
inline constexpr const char** URCS_PAYLOAD_8 = nullptr;
inline constexpr const char** URCS_PAYLOAD_9 = nullptr;
inline constexpr const char* URCS_PAYLOAD_10[] = {
    "<number>",
    "<type>",
    "<class>",
    "<alpha>",
};
inline constexpr const char* URCS_PAYLOAD_11[] = {
    "<number>",
    "<type>",
    "<subaddr>",
    "<satype>",
    "<alphaId>",
    "<CLI validity>",
};
inline constexpr const char* URCS_PAYLOAD_12[] = {
    "<type>",
};
inline constexpr const char* URCS_PAYLOAD_13[] = {
    "<stat>",
    "<lac>",
    "<ci>",
};
inline constexpr const char** URCS_PAYLOAD_14 = nullptr;
inline constexpr const char* URCS_PAYLOAD_15[] = {
    "<mem3>",
    "<index>",
};
inline constexpr const char* URCS_PAYLOAD_16[] = {
    "<oa>",
    "<scts>",
    "<tooa>",
    "<fo>",
    "<pid>",
    "<dcs>",
    "<sca>",
    "<tosca>",
    "<length>",
    "<data>",
};
inline constexpr const char* URCS_PAYLOAD_17[] = {
    "<sn>",
    "<mid>",
    "<dcs>",
    "<page>",
    "<pages>",
    "<data>",
};
inline constexpr const char* URCS_PAYLOAD_18[] = {
    "<fo>",
    "<mr>",
    "<ra>",
    "<tora>",
    "<scts>",
    "<dt>",
    "<st>",
};
inline constexpr const char* URCS_PAYLOAD_19[] = {
    "<number>",
    "<type>",
    "<subaddr>",
    "<satype>",
    "<alphaId>",
};
inline constexpr const char* URCS_PAYLOAD_20[] = {
    "<code2>",
};
inline constexpr const char* URCS_PAYLOAD_21[] = {
    "<code1>",
    "<index>",
};
inline constexpr const char* URCS_PAYLOAD_22[] = {
    "<id1>",
    "<dir>",
    "<stat>",
    "<mode>",
    "<mpty>",
    "<number>",
    "<type>",
    "<alphaID>",
};
inline constexpr const char* URCS_PAYLOAD_23[] = {
    "<mcc>",
    "<mnc>",
    "<full network name>",
    "<full network name CI>",
    "<short network name>",
    "<short network name CI>",
};
inline constexpr const char* URCS_PAYLOAD_24[] = {
    "<year>",
    "<month>",
    "<day>",
    "<hour>",
    "<min>",
    "<sec>",
    "<time zone>",
    "<dst>",
};
inline constexpr const char* URCS_PAYLOAD_25[] = {
    "<time zone>",
};
inline constexpr const char* URCS_PAYLOAD_26[] = {
    "<dst>",
};
inline constexpr const char* URCS_PAYLOAD_27[] = {
    "<n>",
    "<SIM inserted>",
};
inline constexpr const char* URCS_PAYLOAD_28[] = {
    "<type>",
};
inline constexpr const char* URCS_PAYLOAD_29[] = {
    "<state>",
};
inline constexpr const char* URCS_PAYLOAD_30[] = {
    "<cell>",
    "<arfcn>",
    "<rxl>",
    "<rxq>",
    "<mcc>",
    "<mnc>",
    "<bsic>",
    "<cellid>",
    "<rla>",
    "<txp>",
    "<lac>",
    "<TA>",
};
inline constexpr const char** URCS_PAYLOAD_31 = nullptr;
inline constexpr const char** URCS_PAYLOAD_32 = nullptr;
inline constexpr const char* URCS_PAYLOAD_33[] = {
    "<code>",
};
inline constexpr const char* URCS_PAYLOAD_34[] = {
    "<rssi>",
    "<ber>",
};
inline constexpr const char** URCS_PAYLOAD_35 = nullptr;
inline constexpr const char** URCS_PAYLOAD_36 = nullptr;
inline constexpr const char* URCS_PAYLOAD_37[] = {
    "<serv>",
};
inline constexpr const char* URCS_PAYLOAD_38[] = {
    "<n>",
    "<str_urc>",
    "<dcs>",
};
inline constexpr const char* URCS_PAYLOAD_39[] = {
    "<fun>",
};
inline constexpr const char* URCS_PAYLOAD_40[] = {
    "<n>",
};
inline constexpr const char** URCS_PAYLOAD_41 = nullptr;
inline constexpr const char** URCS_PAYLOAD_42 = nullptr;
inline constexpr const char** URCS_PAYLOAD_43 = nullptr;
inline constexpr const char** URCS_PAYLOAD_44 = nullptr;
inline constexpr const char** URCS_PAYLOAD_45 = nullptr;
inline constexpr const char** URCS_PAYLOAD_46 = nullptr;
inline constexpr const char* URCS_PAYLOAD_47[] = {
    "<n>",
    "<length>",
};
inline constexpr const char** URCS_PAYLOAD_48 = nullptr;
inline constexpr const char* URCS_PAYLOAD_49[] = {
    "<IP ADDRESS>",
    "<PORT>",
};
inline constexpr const char* URCS_PAYLOAD_50[] = {
    "<data size>",
    "<TCP/UDP>",
    "<data>",
};
inline constexpr const char* URCS_PAYLOAD_51[] = {
    "<n>",
    "<length>",
};
inline constexpr const char* URCS_PAYLOAD_52[] = {
    "<n>",
    "<len>",
};
inline constexpr const char* URCS_PAYLOAD_53[] = {
    "<status>",
    "<domain name>",
    "<IP>",
    "<IP2>",
};
inline constexpr const char** URCS_PAYLOAD_54 = nullptr;
inline constexpr const char* URCS_PAYLOAD_55[] = {
    "<cid>",
};
inline constexpr const char* URCS_PAYLOAD_56[] = {
    "<Method>",
    "<StatusCode>",
    "<DataLen>",
};
inline constexpr const char* URCS_PAYLOAD_57[] = {
    "<res>",
};
inline constexpr const char* URCS_PAYLOAD_58[] = {
    "<res>",
    "<maxlength>",
};
inline constexpr const char* URCS_PAYLOAD_59[] = {
    "<res>",
};
inline constexpr const char* URCS_PAYLOAD_60[] = {
    "<res>",
    "<size>",
};
inline constexpr const char* URCS_PAYLOAD_61[] = {
    "<res>",
};
inline constexpr const char* URCS_PAYLOAD_62[] = {
    "<res>",
};
inline constexpr const char* URCS_PAYLOAD_63[] = {
    "<res>",
};
inline constexpr const char* URCS_PAYLOAD_64[] = {
    "<code>",
};
inline constexpr const char* URCS_PAYLOAD_65[] = {
    "<cnfLength>",
};
inline constexpr const char* URCS_PAYLOAD_66[] = {
    "<code>",
};
inline constexpr const char* URCS_PAYLOAD_67[] = {
    "<totalNumber>",
    "<totalSize>",
};
inline constexpr const char* URCS_PAYLOAD_68[] = {
    "<msgNumber>",
    "<size>",
};
inline constexpr const char* URCS_PAYLOAD_69[] = {
    "<msgNumber>",
    "<uid>",
};
inline constexpr const char* URCS_PAYLOAD_70[] = {
    "<cnfLength>",
};
inline constexpr const char* URCS_PAYLOAD_71[] = {
    "<cnfLength>",
};
inline constexpr const char** URCS_PAYLOAD_72 = nullptr;
inline constexpr const char** URCS_PAYLOAD_73 = nullptr;
inline constexpr const char* URCS_PAYLOAD_74[] = {
    "<code>",
};
inline constexpr const char* URCS_PAYLOAD_75[] = {
    "<sender>",
    "<time>",
    "<subject>",
    "<size>",
};
inline constexpr const char* URCS_PAYLOAD_76[] = {
    "<mmstype>",
    "<sender>",
    "<receipts>",
    "<ccs>",
    "<bccs>",
    "<datetime>",
    "<subject>",
    "<size>",
};
inline constexpr const char* URCS_PAYLOAD_77[] = {
    "<sender>",
    "<subject>",
    "<transaction>",
    "<location>",
    "<time>",
    "<class>",
    "<size>",
};
inline constexpr const char* URCS_PAYLOAD_78[] = {
    "<status>",
};
inline constexpr const char* URCS_PAYLOAD_79[] = {
    "<pci_type>",
    "<proactive_command>",
};
inline constexpr const char* URCS_PAYLOAD_80[] = {
    "<key>",
    "<last time>",
};
inline constexpr const char* URCS_PAYLOAD_81[] = {
    "<status>",
    "<id>",
    "<form>",
    "<time>",
    "<len>",
};
inline constexpr const char* URCS_PAYLOAD_82[] = {
    "<status>",
};
inline constexpr const char* URCS_PAYLOAD_83[] = {
    "<stat>",
    "<lac>",
    "<ci>",
};
inline constexpr const char* URCS_PAYLOAD_84[] = {
    "<PDP_type>",
    "<PDP_addr>",
    "<cid>",
};
inline constexpr const char* URCS_PAYLOAD_85[] = {
    "<PDP_type>",
    "<PDP_addr>",
    "<cid>",
};
inline constexpr const char** URCS_PAYLOAD_86 = nullptr;
inline constexpr const char** URCS_PAYLOAD_87 = nullptr;
inline constexpr const char* URCS_PAYLOAD_88[] = {
    "<n>",
};
inline constexpr const char** URCS_PAYLOAD_89 = nullptr;
inline constexpr const char** URCS_PAYLOAD_90 = nullptr;
inline constexpr const char* URCS_PAYLOAD_91[] = {
    "<value>",
    "<event>",
};
inline constexpr const char* URCS_PAYLOAD_92[] = {
    "<status>",
};
inline constexpr const char* URCS_PAYLOAD_93[] = {
    "<status>",
    "<mode>",
    "<var>",
    "<display>",
    "<result>",
};
inline constexpr const char* URCS_PAYLOAD_94[] = {
    "<MCC>",
    "<MNC>",
    "<Arfcn>",
    "<Rxlev>",
    "<CellID>",
    "<Lac>",
    "<Bsic>",
};
inline constexpr const char** URCS_EB_0 = nullptr;
inline constexpr const char** URCS_EB_1 = nullptr;
inline constexpr const char* URCS_EB_2[] = {
    "AT+CPOWD",
};
inline constexpr const char** URCS_EB_3 = nullptr;
inline constexpr const char** URCS_EB_4 = nullptr;
inline constexpr const char** URCS_EB_5 = nullptr;
inline constexpr const char** URCS_EB_6 = nullptr;
inline constexpr const char** URCS_EB_7 = nullptr;
inline constexpr const char* URCS_EB_8[] = {
    "AT+CIURC",
};
inline constexpr const char** URCS_EB_9 = nullptr;
inline constexpr const char* URCS_EB_10[] = {
    "AT+CCWA",
};
inline constexpr const char* URCS_EB_11[] = {
    "AT+CLIP",
};
inline constexpr const char* URCS_EB_12[] = {
    "AT+CRC",
};
inline constexpr const char* URCS_EB_13[] = {
    "AT+CREG",
};
inline constexpr const char* URCS_EB_14[] = {
    "AT+CCWE",
};
inline constexpr const char* URCS_EB_15[] = {
    "AT+CNMI",
};
inline constexpr const char* URCS_EB_16[] = {
    "AT+CNMI",
};
inline constexpr const char* URCS_EB_17[] = {
    "AT+CNMI",
};
inline constexpr const char* URCS_EB_18[] = {
    "AT+CNMI",
};
inline constexpr const char* URCS_EB_19[] = {
    "AT+COLP",
};
inline constexpr const char* URCS_EB_20[] = {
    "AT+CSSN",
};
inline constexpr const char* URCS_EB_21[] = {
    "AT+CSSN",
};
inline constexpr const char* URCS_EB_22[] = {
    "AT+CLCC",
};
inline constexpr const char* URCS_EB_23[] = {
    "AT+CLTS",
};
inline constexpr const char* URCS_EB_24[] = {
    "AT+CLTS",
};
inline constexpr const char* URCS_EB_25[] = {
    "AT+CLTS",
};
inline constexpr const char* URCS_EB_26[] = {
    "AT+CLTS",
};
inline constexpr const char* URCS_EB_27[] = {
    "AT+CSMINS",
};
inline constexpr const char* URCS_EB_28[] = {
    "AT+CDRIND",
};
inline constexpr const char* URCS_EB_29[] = {
    "AT+CHF",
};
inline constexpr const char* URCS_EB_30[] = {
    "AT+CENG",
};
inline constexpr const char* URCS_EB_31[] = {
    "AT+MORING",
};
inline constexpr const char* URCS_EB_32[] = {
    "AT+MORING",
};
inline constexpr const char* URCS_EB_33[] = {
    "AT+CPIN",
};
inline constexpr const char* URCS_EB_34[] = {
    "AT+EXUNSOL",
};
inline constexpr const char* URCS_EB_35[] = {
    "AT+SIMTONE",
};
inline constexpr const char* URCS_EB_36[] = {
    "AT+STTONE",
};
inline constexpr const char* URCS_EB_37[] = {
    "AT+CR",
};
inline constexpr const char* URCS_EB_38[] = {
    "AT+CUSD",
};
inline constexpr const char* URCS_EB_39[] = {
    "AT+CFUN",
};
inline constexpr const char* URCS_EB_40[] = {
    "AT+CMTE",
};
inline constexpr const char* URCS_EB_41[] = {
    "AT+CIPSTART",
};
inline constexpr const char** URCS_EB_42 = nullptr;
inline constexpr const char* URCS_EB_43[] = {
    "AT+CIPSTART",
};
inline constexpr const char* URCS_EB_44[] = {
    "AT+CIPSTART",
};
inline constexpr const char* URCS_EB_45[] = {
    "AT+CIPSEND",
};
inline constexpr const char* URCS_EB_46[] = {
    "AT+CIPSEND",
};
inline constexpr const char* URCS_EB_47[] = {
    "AT+CIPSEND",
    "AT+CIPQSEND",
};
inline constexpr const char* URCS_EB_48[] = {
    "AT+CIPCLOSE",
};
inline constexpr const char* URCS_EB_49[] = {
    "AT+CIPSRIP",
};
inline constexpr const char* URCS_EB_50[] = {
    "AT+CIPHEAD",
    "AT+CIPSHOWTP",
};
inline constexpr const char* URCS_EB_51[] = {
    "AT+CIPHEAD",
};
inline constexpr const char* URCS_EB_52[] = {
    "AT+CIPRXGET",
};
inline constexpr const char* URCS_EB_53[] = {
    "AT+CDNSGIP",
};
inline constexpr const char** URCS_EB_54 = nullptr;
inline constexpr const char* URCS_EB_55[] = {
    "AT+SAPBR",
};
inline constexpr const char* URCS_EB_56[] = {
    "AT+HTTPACTION",
};
inline constexpr const char* URCS_EB_57[] = {
    "AT+FTPGET",
};
inline constexpr const char* URCS_EB_58[] = {
    "AT+FTPPUT",
};
inline constexpr const char* URCS_EB_59[] = {
    "AT+FTPDELE",
};
inline constexpr const char* URCS_EB_60[] = {
    "AT+FTPSIZE",
};
inline constexpr const char* URCS_EB_61[] = {
    "AT+FTPMKD",
};
inline constexpr const char* URCS_EB_62[] = {
    "AT+FTPRMD",
};
inline constexpr const char* URCS_EB_63[] = {
    "AT+FTPLIST",
};
inline constexpr const char* URCS_EB_64[] = {
    "AT+SMTPSEND",
};
inline constexpr const char* URCS_EB_65[] = {
    "AT+SMTPFT",
};
inline constexpr const char* URCS_EB_66[] = {
    "AT+POP3IN",
};
inline constexpr const char* URCS_EB_67[] = {
    "AT+POP3NUM",
};
inline constexpr const char* URCS_EB_68[] = {
    "AT+POP3LIST",
};
inline constexpr const char* URCS_EB_69[] = {
    "AT+POP3UIDL",
};
inline constexpr const char* URCS_EB_70[] = {
    "AT+POP3CMD",
};
inline constexpr const char* URCS_EB_71[] = {
    "AT+POP3READ",
};
inline constexpr const char* URCS_EB_72[] = {
    "AT+POP3DEL",
};
inline constexpr const char* URCS_EB_73[] = {
    "AT+POP3RSET",
};
inline constexpr const char* URCS_EB_74[] = {
    "AT+POP3OUT",
};
inline constexpr const char* URCS_EB_75[] = {
    "AT+CMMSRECV",
};
inline constexpr const char* URCS_EB_76[] = {
    "AT+CMMSVIEW",
};
inline constexpr const char* URCS_EB_77[] = {
    "AT+CMMSRDPUSH",
};
inline constexpr const char* URCS_EB_78[] = {
    "AT+CMMSSTATUS",
};
inline constexpr const char* URCS_EB_79[] = {
    "AT+STKPCIS",
};
inline constexpr const char* URCS_EB_80[] = {
    "AT+DDET",
};
inline constexpr const char* URCS_EB_81[] = {
    "AT+CREC",
};
inline constexpr const char* URCS_EB_82[] = {
    "AT+CTTS",
};
inline constexpr const char* URCS_EB_83[] = {
    "AT+CGREG",
};
inline constexpr const char* URCS_EB_84[] = {
    "AT+CGEREP",
};
inline constexpr const char* URCS_EB_85[] = {
    "AT+CGEREP",
};
inline constexpr const char* URCS_EB_86[] = {
    "AT+CGEREP",
};
inline constexpr const char* URCS_EB_87[] = {
    "AT+CGEREP",
};
inline constexpr const char* URCS_EB_88[] = {
    "AT+CALA",
};
inline constexpr const char* URCS_EB_89[] = {
    "AT+CMEDPLAY",
};
inline constexpr const char* URCS_EB_90[] = {
    "AT+SIMTONEX",
};
inline constexpr const char* URCS_EB_91[] = {
    "AT+SKPD",
};
inline constexpr const char* URCS_EB_92[] = {
    "AT+CANT",
};
inline constexpr const char* URCS_EB_93[] = {
    "AT+SJDR",
};
inline constexpr const char* URCS_EB_94[] = {
    "AT+CELLIST",
};

inline constexpr URC URCS[] = {
    {
        "RING",
        Category::V25TER,
        "An incoming call signal from network is detected",
        URCS_PAYLOAD_0, 0,
        URCS_EB_0, 0,
        URCS_SUPPORT_0,
        "V1.12 §18.3"
    },
    {
        "RDY",
        Category::V25TER,
        "Power on procedure is completed",
        URCS_PAYLOAD_1, 0,
        URCS_EB_1, 0,
        URCS_SUPPORT_1,
        "V1.12 §18.3"
    },
    {
        "NORMAL POWER DOWN",
        Category::V25TER,
        "SIM800 is powered down by PWRKEY or AT+CPOWD=1",
        URCS_PAYLOAD_2, 0,
        URCS_EB_2, 1,
        URCS_SUPPORT_2,
        "V1.12 §18.3"
    },
    {
        "UNDER-VOLTAGE POWER DOWN",
        Category::V25TER,
        "Under-voltage automatic power down",
        URCS_PAYLOAD_3, 0,
        URCS_EB_3, 0,
        URCS_SUPPORT_3,
        "V1.12 §18.3"
    },
    {
        "UNDER-VOLTAGE WARNNING",
        Category::V25TER,
        "Under-voltage warning",
        URCS_PAYLOAD_4, 0,
        URCS_EB_4, 0,
        URCS_SUPPORT_4,
        "V1.12 §18.3"
    },
    {
        "OVER-VOLTAGE POWER DOWN",
        Category::V25TER,
        "Over-voltage automatic power down",
        URCS_PAYLOAD_5, 0,
        URCS_EB_5, 0,
        URCS_SUPPORT_5,
        "V1.12 §18.3"
    },
    {
        "OVER-VOLTAGE WARNNING",
        Category::V25TER,
        "Over-voltage warning",
        URCS_PAYLOAD_6, 0,
        URCS_EB_6, 0,
        URCS_SUPPORT_6,
        "V1.12 §18.3"
    },
    {
        "CHARGE-ONLY MODE",
        Category::V25TER,
        "The module is charging by charger",
        URCS_PAYLOAD_7, 0,
        URCS_EB_7, 0,
        URCS_SUPPORT_7,
        "V1.12 §18.3"
    },
    {
        "Call Ready",
        Category::V25TER,
        "Module is powered on and phonebook initialization is over",
        URCS_PAYLOAD_8, 0,
        URCS_EB_8, 1,
        URCS_SUPPORT_8,
        "V1.12 §18.3"
    },
    {
        "SMS Ready",
        Category::V25TER,
        "Module is powered on and SMS initialization is over",
        URCS_PAYLOAD_9, 0,
        URCS_EB_9, 0,
        URCS_SUPPORT_9,
        "V1.12 §18.3"
    },
    {
        "+CCWA",
        Category::cat_3GPP_27007,
        "Indication of a call that is currently waiting and can be accepted",
        URCS_PAYLOAD_10, 4,
        URCS_EB_10, 1,
        URCS_SUPPORT_10,
        "V1.12 §18.3"
    },
    {
        "+CLIP",
        Category::cat_3GPP_27007,
        "The calling line identity of the calling party",
        URCS_PAYLOAD_11, 6,
        URCS_EB_11, 1,
        URCS_SUPPORT_11,
        "V1.12 §18.3"
    },
    {
        "+CRING",
        Category::cat_3GPP_27007,
        "Indicates incoming call to the TE if extended format is enabled",
        URCS_PAYLOAD_12, 1,
        URCS_EB_12, 1,
        URCS_SUPPORT_12,
        "V1.12 §18.3"
    },
    {
        "+CREG",
        Category::cat_3GPP_27007,
        "There is a change in the MT network registration status",
        URCS_PAYLOAD_13, 3,
        URCS_EB_13, 1,
        URCS_SUPPORT_13,
        "V1.12 §18.3"
    },
    {
        "+CCWV",
        Category::cat_3GPP_27007,
        "Shortly before the ACM maximum value is reached",
        URCS_PAYLOAD_14, 0,
        URCS_EB_14, 1,
        URCS_SUPPORT_14,
        "V1.12 §18.3"
    },
    {
        "+CMTI",
        Category::cat_3GPP_27007,
        "Indicates that new message has been received",
        URCS_PAYLOAD_15, 2,
        URCS_EB_15, 1,
        URCS_SUPPORT_15,
        "V1.12 §18.3"
    },
    {
        "+CMT",
        Category::cat_3GPP_27007,
        "Indicates that new message has been received",
        URCS_PAYLOAD_16, 10,
        URCS_EB_16, 1,
        URCS_SUPPORT_16,
        "V1.12 §18.3"
    },
    {
        "+CBM",
        Category::cat_3GPP_27007,
        "Indicates that new cell broadcast message has been received",
        URCS_PAYLOAD_17, 6,
        URCS_EB_17, 1,
        URCS_SUPPORT_17,
        "V1.12 §18.3"
    },
    {
        "+CDS",
        Category::cat_3GPP_27007,
        "Indicates that new SMS status report has been received",
        URCS_PAYLOAD_18, 7,
        URCS_EB_18, 1,
        URCS_SUPPORT_18,
        "V1.12 §18.3"
    },
    {
        "+COLP",
        Category::cat_3GPP_27007,
        "The presentation of the COL at the TE for a MO call",
        URCS_PAYLOAD_19, 5,
        URCS_EB_19, 1,
        URCS_SUPPORT_19,
        "V1.12 §18.3"
    },
    {
        "+CSSU",
        Category::cat_3GPP_27007,
        "Presentation status during a mobile terminated call setup",
        URCS_PAYLOAD_20, 1,
        URCS_EB_20, 1,
        URCS_SUPPORT_20,
        "V1.12 §18.3"
    },
    {
        "+CSSI",
        Category::cat_3GPP_27007,
        "Presentation status after a mobile originated call setup",
        URCS_PAYLOAD_21, 2,
        URCS_EB_21, 1,
        URCS_SUPPORT_21,
        "V1.12 §18.3"
    },
    {
        "+CLCC",
        Category::cat_3GPP_27007,
        "Report a list of current calls of ME",
        URCS_PAYLOAD_22, 8,
        URCS_EB_22, 1,
        URCS_SUPPORT_22,
        "V1.12 §18.3"
    },
    {
        "*PSNWID",
        Category::cat_3GPP_27007,
        "Refresh network name by network",
        URCS_PAYLOAD_23, 6,
        URCS_EB_23, 1,
        URCS_SUPPORT_23,
        "V1.12 §18.3"
    },
    {
        "*PSUTTZ",
        Category::cat_3GPP_27007,
        "Refresh time and time zone by network",
        URCS_PAYLOAD_24, 8,
        URCS_EB_24, 1,
        URCS_SUPPORT_24,
        "V1.12 §18.3"
    },
    {
        "+CTZV",
        Category::cat_3GPP_27007,
        "Refresh network time zone by network",
        URCS_PAYLOAD_25, 1,
        URCS_EB_25, 1,
        URCS_SUPPORT_25,
        "V1.12 §18.3"
    },
    {
        "DST",
        Category::cat_3GPP_27007,
        "Refresh Network Daylight Saving Time by network",
        URCS_PAYLOAD_26, 1,
        URCS_EB_26, 1,
        URCS_SUPPORT_26,
        "V1.12 §18.3"
    },
    {
        "+CSMINS",
        Category::cat_3GPP_27007,
        "Indicates whether SIM card has been inserted",
        URCS_PAYLOAD_27, 2,
        URCS_EB_27, 1,
        URCS_SUPPORT_27,
        "V1.12 §18.3"
    },
    {
        "+CDRIND",
        Category::cat_3GPP_27007,
        "Indicates whether a CS voice call, CS data has been terminated",
        URCS_PAYLOAD_28, 1,
        URCS_EB_28, 1,
        URCS_SUPPORT_28,
        "V1.12 §18.3"
    },
    {
        "+CHF",
        Category::cat_3GPP_27007,
        "Indicates the current channel",
        URCS_PAYLOAD_29, 1,
        URCS_EB_29, 1,
        URCS_SUPPORT_29,
        "V1.12 §18.3"
    },
    {
        "+CENG",
        Category::cat_3GPP_27007,
        "Report of network information",
        URCS_PAYLOAD_30, 12,
        URCS_EB_30, 1,
        URCS_SUPPORT_30,
        "V1.12 §18.3"
    },
    {
        "MO RING",
        Category::cat_3GPP_27007,
        "Shows call state of MO call: the call is alerted",
        URCS_PAYLOAD_31, 0,
        URCS_EB_31, 1,
        URCS_SUPPORT_31,
        "V1.12 §18.3"
    },
    {
        "MO CONNECTED",
        Category::cat_3GPP_27007,
        "Shows call state of MO call: the call is established",
        URCS_PAYLOAD_32, 0,
        URCS_EB_32, 1,
        URCS_SUPPORT_32,
        "V1.12 §18.3"
    },
    {
        "+CPIN",
        Category::cat_3GPP_27007,
        "Indicates whether some password is required or not",
        URCS_PAYLOAD_33, 1,
        URCS_EB_33, 1,
        URCS_SUPPORT_33,
        "V1.12 §18.3"
    },
    {
        "+CSQN",
        Category::cat_3GPP_27007,
        "Displays signal strength and channel bit error rate",
        URCS_PAYLOAD_34, 2,
        URCS_EB_34, 1,
        URCS_SUPPORT_34,
        "V1.12 §18.3"
    },
    {
        "+SIMTONE",
        Category::SIMCom,
        "The generated tone playing is stopped or completed",
        URCS_PAYLOAD_35, 0,
        URCS_EB_35, 1,
        URCS_SUPPORT_35,
        "V1.12 §18.3"
    },
    {
        "+STTONE",
        Category::SIMCom,
        "The SIM Toolkit tone playing is stopped or completed",
        URCS_PAYLOAD_36, 0,
        URCS_EB_36, 1,
        URCS_SUPPORT_36,
        "V1.12 §18.3"
    },
    {
        "+CR",
        Category::cat_3GPP_27007,
        "Intermediate result code during connect negotiation",
        URCS_PAYLOAD_37, 1,
        URCS_EB_37, 1,
        URCS_SUPPORT_37,
        "V1.12 §18.3"
    },
    {
        "+CUSD",
        Category::cat_3GPP_27007,
        "Indicates a USSD response from the network",
        URCS_PAYLOAD_38, 3,
        URCS_EB_38, 1,
        URCS_SUPPORT_38,
        "V1.12 §18.3"
    },
    {
        "+CFUN",
        Category::cat_3GPP_27007,
        "Phone functionality indication",
        URCS_PAYLOAD_39, 1,
        URCS_EB_39, 1,
        URCS_SUPPORT_39,
        "V1.12 §18.3"
    },
    {
        "+CMTE",
        Category::SIMCom,
        "The module temperature is abnormal",
        URCS_PAYLOAD_40, 1,
        URCS_EB_40, 1,
        URCS_SUPPORT_40,
        "V1.12 §18.3"
    },
    {
        "CONNECT OK",
        Category::TCPIP,
        "TCP/UDP connection is successful",
        URCS_PAYLOAD_41, 0,
        URCS_EB_41, 1,
        URCS_SUPPORT_41,
        "V1.12 §18.3"
    },
    {
        "CONNECT",
        Category::TCPIP,
        "TCP/UDP connection in channel mode is successful",
        URCS_PAYLOAD_42, 0,
        URCS_EB_42, 0,
        URCS_SUPPORT_42,
        "V1.12 §18.3"
    },
    {
        "CONNECT FAIL",
        Category::TCPIP,
        "TCP/UDP connection fails",
        URCS_PAYLOAD_43, 0,
        URCS_EB_43, 1,
        URCS_SUPPORT_43,
        "V1.12 §18.3"
    },
    {
        "ALREADY CONNECT",
        Category::TCPIP,
        "TCP/UDP connection exists",
        URCS_PAYLOAD_44, 0,
        URCS_EB_44, 1,
        URCS_SUPPORT_44,
        "V1.12 §18.3"
    },
    {
        "SEND OK",
        Category::TCPIP,
        "Data sending is successful",
        URCS_PAYLOAD_45, 0,
        URCS_EB_45, 1,
        URCS_SUPPORT_45,
        "V1.12 §18.3"
    },
    {
        "SEND FAIL",
        Category::TCPIP,
        "Data sending fails",
        URCS_PAYLOAD_46, 0,
        URCS_EB_46, 1,
        URCS_SUPPORT_46,
        "V1.12 §18.3"
    },
    {
        "DATA ACCEPT",
        Category::TCPIP,
        "Data accepted in quick send mode",
        URCS_PAYLOAD_47, 2,
        URCS_EB_47, 2,
        URCS_SUPPORT_47,
        "V1.12 §18.3"
    },
    {
        "CLOSED",
        Category::TCPIP,
        "TCP/UDP connection is closed",
        URCS_PAYLOAD_48, 0,
        URCS_EB_48, 1,
        URCS_SUPPORT_48,
        "V1.12 §18.3"
    },
    {
        "RECV FROM",
        Category::TCPIP,
        "Shows remote IP address and port (single connection mode)",
        URCS_PAYLOAD_49, 2,
        URCS_EB_49, 1,
        URCS_SUPPORT_49,
        "V1.12 §18.3"
    },
    {
        "+IPD",
        Category::TCPIP,
        "Display transfer protocol in IP header to received data",
        URCS_PAYLOAD_50, 3,
        URCS_EB_50, 2,
        URCS_SUPPORT_50,
        "V1.12 §18.3"
    },
    {
        "+RECEIVE",
        Category::TCPIP,
        "Received data from remote client (multi connection mode)",
        URCS_PAYLOAD_51, 2,
        URCS_EB_51, 1,
        URCS_SUPPORT_51,
        "V1.12 §18.3"
    },
    {
        "+CIPRXGET",
        Category::TCPIP,
        "Data received from network manually",
        URCS_PAYLOAD_52, 2,
        URCS_EB_52, 1,
        URCS_SUPPORT_52,
        "V1.12 §8.2.26"
    },
    {
        "+CDNSGIP",
        Category::TCPIP,
        "DNS resolution result",
        URCS_PAYLOAD_53, 4,
        URCS_EB_53, 1,
        URCS_SUPPORT_53,
        "V1.12 §18.3"
    },
    {
        "+PDP: DEACT",
        Category::GPRS,
        "GPRS is disconnected by network",
        URCS_PAYLOAD_54, 0,
        URCS_EB_54, 0,
        URCS_SUPPORT_54,
        "V1.12 §18.3"
    },
    {
        "+SAPBR",
        Category::IP,
        "The bearer based on IP connection is deactivated",
        URCS_PAYLOAD_55, 1,
        URCS_EB_55, 1,
        URCS_SUPPORT_55,
        "V1.12 §18.3"
    },
    {
        "+HTTPACTION",
        Category::HTTP,
        "Indicates HTTP method, Status Code and length of data",
        URCS_PAYLOAD_56, 3,
        URCS_EB_56, 1,
        URCS_SUPPORT_56,
        "V1.12 §18.3"
    },
    {
        "+FTPGET",
        Category::FTP,
        "FTP GET session status",
        URCS_PAYLOAD_57, 1,
        URCS_EB_57, 1,
        URCS_SUPPORT_57,
        "V1.12 §18.3"
    },
    {
        "+FTPPUT",
        Category::FTP,
        "FTP PUT return result",
        URCS_PAYLOAD_58, 2,
        URCS_EB_58, 1,
        URCS_SUPPORT_58,
        "V1.12 §18.3"
    },
    {
        "+FTPDELE",
        Category::FTP,
        "FTP delete session result",
        URCS_PAYLOAD_59, 1,
        URCS_EB_59, 1,
        URCS_SUPPORT_59,
        "V1.12 §18.3"
    },
    {
        "+FTPSIZE",
        Category::FTP,
        "FTP size session result",
        URCS_PAYLOAD_60, 2,
        URCS_EB_60, 1,
        URCS_SUPPORT_60,
        "V1.12 §18.3"
    },
    {
        "+FTPMKD",
        Category::FTP,
        "FTP create directory result",
        URCS_PAYLOAD_61, 1,
        URCS_EB_61, 1,
        URCS_SUPPORT_61,
        "V1.12 §18.3"
    },
    {
        "+FTPRMD",
        Category::FTP,
        "FTP delete directory result",
        URCS_PAYLOAD_62, 1,
        URCS_EB_62, 1,
        URCS_SUPPORT_62,
        "V1.12 §18.3"
    },
    {
        "+FTPLIST",
        Category::FTP,
        "FTP list session result",
        URCS_PAYLOAD_63, 1,
        URCS_EB_63, 1,
        URCS_SUPPORT_63,
        "V1.12 §18.3"
    },
    {
        "+SMTPSEND",
        Category::Email,
        "Email send result",
        URCS_PAYLOAD_64, 1,
        URCS_EB_64, 1,
        URCS_SUPPORT_64,
        "V1.12 §18.3"
    },
    {
        "+SMTPFT",
        Category::Email,
        "Email attachment transfer",
        URCS_PAYLOAD_65, 1,
        URCS_EB_65, 1,
        URCS_SUPPORT_65,
        "V1.12 §18.3"
    },
    {
        "+POP3IN",
        Category::Email,
        "POP3 login result",
        URCS_PAYLOAD_66, 1,
        URCS_EB_66, 1,
        URCS_SUPPORT_66,
        "V1.12 §18.3"
    },
    {
        "+POP3NUM",
        Category::Email,
        "POP3 message number result",
        URCS_PAYLOAD_67, 2,
        URCS_EB_67, 1,
        URCS_SUPPORT_67,
        "V1.12 §18.3"
    },
    {
        "+POP3LIST",
        Category::Email,
        "POP3 message size result",
        URCS_PAYLOAD_68, 2,
        URCS_EB_68, 1,
        URCS_SUPPORT_68,
        "V1.12 §18.3"
    },
    {
        "+POP3UIDL",
        Category::Email,
        "POP3 unique-id result",
        URCS_PAYLOAD_69, 2,
        URCS_EB_69, 1,
        URCS_SUPPORT_69,
        "V1.12 §18.3"
    },
    {
        "+POP3CMD",
        Category::Email,
        "POP3 command result",
        URCS_PAYLOAD_70, 1,
        URCS_EB_70, 1,
        URCS_SUPPORT_70,
        "V1.12 §18.3"
    },
    {
        "+POP3READ",
        Category::Email,
        "POP3 read multi-line result",
        URCS_PAYLOAD_71, 1,
        URCS_EB_71, 1,
        URCS_SUPPORT_71,
        "V1.12 §18.3"
    },
    {
        "+POP3DEL",
        Category::Email,
        "POP3 delete result",
        URCS_PAYLOAD_72, 0,
        URCS_EB_72, 1,
        URCS_SUPPORT_72,
        "V1.12 §18.3"
    },
    {
        "+POP3RSET",
        Category::Email,
        "POP3 reset result",
        URCS_PAYLOAD_73, 0,
        URCS_EB_73, 1,
        URCS_SUPPORT_73,
        "V1.12 §18.3"
    },
    {
        "+POP3OUT",
        Category::Email,
        "POP3 logout result",
        URCS_PAYLOAD_74, 1,
        URCS_EB_74, 1,
        URCS_SUPPORT_74,
        "V1.12 §18.3"
    },
    {
        "+CMMSRECV",
        Category::MMS,
        "MMS receive result",
        URCS_PAYLOAD_75, 4,
        URCS_EB_75, 1,
        URCS_SUPPORT_75,
        "V1.12 §18.3"
    },
    {
        "+CMMSVIEW",
        Category::MMS,
        "MMS view result",
        URCS_PAYLOAD_76, 8,
        URCS_EB_76, 1,
        URCS_SUPPORT_76,
        "V1.12 §18.3"
    },
    {
        "+CMMSRDPUSH",
        Category::MMS,
        "MMS push read result",
        URCS_PAYLOAD_77, 7,
        URCS_EB_77, 1,
        URCS_SUPPORT_77,
        "V1.12 §18.3"
    },
    {
        "+CMMSSTATUS",
        Category::MMS,
        "MMS status result",
        URCS_PAYLOAD_78, 1,
        URCS_EB_78, 1,
        URCS_SUPPORT_78,
        "V1.12 §18.3"
    },
    {
        "+STKPCI",
        Category::STK,
        "STK proactive command indication",
        URCS_PAYLOAD_79, 2,
        URCS_EB_79, 1,
        URCS_SUPPORT_79,
        "V1.12 §18.3"
    },
    {
        "+DTMF",
        Category::DDET,
        "DTMF key detection",
        URCS_PAYLOAD_80, 2,
        URCS_EB_80, 1,
        URCS_SUPPORT_80,
        "V1.12 §18.3"
    },
    {
        "+CREC",
        Category::RECORD,
        "Record operation result",
        URCS_PAYLOAD_81, 5,
        URCS_EB_81, 1,
        URCS_SUPPORT_81,
        "V1.12 §18.3"
    },
    {
        "+CTTS",
        Category::TTS,
        "TTS play over indication",
        URCS_PAYLOAD_82, 1,
        URCS_EB_82, 1,
        URCS_SUPPORT_82,
        "V1.12 §18.3"
    },
    {
        "+CGREG",
        Category::GPRS,
        "Network registration status change",
        URCS_PAYLOAD_83, 3,
        URCS_EB_83, 1,
        URCS_SUPPORT_83,
        "V1.12 §18.3"
    },
    {
        "+CGEV: NW DEACT",
        Category::GPRS,
        "Network deactivation event",
        URCS_PAYLOAD_84, 3,
        URCS_EB_84, 1,
        URCS_SUPPORT_84,
        "V1.12 §18.3"
    },
    {
        "+CGEV: ME DEACT",
        Category::GPRS,
        "Mobile equipment deactivation event",
        URCS_PAYLOAD_85, 3,
        URCS_EB_85, 1,
        URCS_SUPPORT_85,
        "V1.12 §18.3"
    },
    {
        "+CGEV: NW DETACH",
        Category::GPRS,
        "Network detach event",
        URCS_PAYLOAD_86, 0,
        URCS_EB_86, 1,
        URCS_SUPPORT_86,
        "V1.12 §18.3"
    },
    {
        "+CGEV: ME DETACH",
        Category::GPRS,
        "Mobile equipment detach event",
        URCS_PAYLOAD_87, 0,
        URCS_EB_87, 1,
        URCS_SUPPORT_87,
        "V1.12 §18.3"
    },
    {
        "ALARM RING",
        Category::SIMCom,
        "Indicate expired alarm",
        URCS_PAYLOAD_88, 1,
        URCS_EB_88, 1,
        URCS_SUPPORT_88,
        "V1.12 §18.3"
    },
    {
        "+CMEDPLAY",
        Category::SIMCom,
        "Audio play over",
        URCS_PAYLOAD_89, 0,
        URCS_EB_89, 1,
        URCS_SUPPORT_89,
        "V1.12 §6.2.71"
    },
    {
        "+SIMTONEX",
        Category::SIMCom,
        "Custom tone playing is stopped or completed",
        URCS_PAYLOAD_90, 0,
        URCS_EB_90, 1,
        URCS_SUPPORT_90,
        "V1.12 §6.2.65"
    },
    {
        "+SKPD",
        Category::SIMCom,
        "Keypad pressed or released event",
        URCS_PAYLOAD_91, 2,
        URCS_EB_91, 1,
        URCS_SUPPORT_91,
        "V1.12 §6.2.64"
    },
    {
        "+CANT",
        Category::SIMCom,
        "Antenna state report",
        URCS_PAYLOAD_92, 1,
        URCS_EB_92, 1,
        URCS_SUPPORT_92,
        "V1.12 §6.2.61"
    },
    {
        "+SJDR",
        Category::SIMCom,
        "Jamming detection status",
        URCS_PAYLOAD_93, 5,
        URCS_EB_93, 1,
        URCS_SUPPORT_93,
        "V1.12 §6.2.58"
    },
    {
        "+CELLIST",
        Category::SIMCom,
        "Cell information report",
        URCS_PAYLOAD_94, 7,
        URCS_EB_94, 1,
        URCS_SUPPORT_94,
        "V1.12 §6.2.79"
    },
};

inline constexpr std::size_t URC_COUNT = 95;

inline constexpr URC URCS_BY_CAT_V25TER_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
};
inline constexpr const URC* const URCS_BY_CAT_V25TER = URCS_BY_CAT_V25TER_DATA;
inline constexpr std::size_t URCS_BY_CAT_V25TER_COUNT = 10;

inline constexpr URC URCS_BY_CAT_cat_3GPP_27007_DATA[] = {
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[37],
    URCS[38],
    URCS[39],
};
inline constexpr const URC* const URCS_BY_CAT_cat_3GPP_27007 = URCS_BY_CAT_cat_3GPP_27007_DATA;
inline constexpr std::size_t URCS_BY_CAT_cat_3GPP_27007_COUNT = 28;

inline constexpr const URC* const URCS_BY_CAT_cat_3GPP_27005 = nullptr;
inline constexpr std::size_t URCS_BY_CAT_cat_3GPP_27005_COUNT = 0;

inline constexpr URC URCS_BY_CAT_STK_DATA[] = {
    URCS[79],
};
inline constexpr const URC* const URCS_BY_CAT_STK = URCS_BY_CAT_STK_DATA;
inline constexpr std::size_t URCS_BY_CAT_STK_COUNT = 1;

inline constexpr URC URCS_BY_CAT_SIMCom_DATA[] = {
    URCS[35],
    URCS[36],
    URCS[40],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_CAT_SIMCom = URCS_BY_CAT_SIMCom_DATA;
inline constexpr std::size_t URCS_BY_CAT_SIMCom_COUNT = 10;

inline constexpr URC URCS_BY_CAT_GPRS_DATA[] = {
    URCS[54],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
};
inline constexpr const URC* const URCS_BY_CAT_GPRS = URCS_BY_CAT_GPRS_DATA;
inline constexpr std::size_t URCS_BY_CAT_GPRS_COUNT = 6;

inline constexpr URC URCS_BY_CAT_TCPIP_DATA[] = {
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
};
inline constexpr const URC* const URCS_BY_CAT_TCPIP = URCS_BY_CAT_TCPIP_DATA;
inline constexpr std::size_t URCS_BY_CAT_TCPIP_COUNT = 13;

inline constexpr URC URCS_BY_CAT_IP_DATA[] = {
    URCS[55],
};
inline constexpr const URC* const URCS_BY_CAT_IP = URCS_BY_CAT_IP_DATA;
inline constexpr std::size_t URCS_BY_CAT_IP_COUNT = 1;

inline constexpr const URC* const URCS_BY_CAT_PING = nullptr;
inline constexpr std::size_t URCS_BY_CAT_PING_COUNT = 0;

inline constexpr URC URCS_BY_CAT_HTTP_DATA[] = {
    URCS[56],
};
inline constexpr const URC* const URCS_BY_CAT_HTTP = URCS_BY_CAT_HTTP_DATA;
inline constexpr std::size_t URCS_BY_CAT_HTTP_COUNT = 1;

inline constexpr URC URCS_BY_CAT_FTP_DATA[] = {
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
};
inline constexpr const URC* const URCS_BY_CAT_FTP = URCS_BY_CAT_FTP_DATA;
inline constexpr std::size_t URCS_BY_CAT_FTP_COUNT = 7;

inline constexpr const URC* const URCS_BY_CAT_GSM_Location = nullptr;
inline constexpr std::size_t URCS_BY_CAT_GSM_Location_COUNT = 0;

inline constexpr URC URCS_BY_CAT_Email_DATA[] = {
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
};
inline constexpr const URC* const URCS_BY_CAT_Email = URCS_BY_CAT_Email_DATA;
inline constexpr std::size_t URCS_BY_CAT_Email_COUNT = 11;

inline constexpr URC URCS_BY_CAT_MMS_DATA[] = {
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
};
inline constexpr const URC* const URCS_BY_CAT_MMS = URCS_BY_CAT_MMS_DATA;
inline constexpr std::size_t URCS_BY_CAT_MMS_COUNT = 4;

inline constexpr URC URCS_BY_CAT_DDET_DATA[] = {
    URCS[80],
};
inline constexpr const URC* const URCS_BY_CAT_DDET = URCS_BY_CAT_DDET_DATA;
inline constexpr std::size_t URCS_BY_CAT_DDET_COUNT = 1;

inline constexpr URC URCS_BY_CAT_RECORD_DATA[] = {
    URCS[81],
};
inline constexpr const URC* const URCS_BY_CAT_RECORD = URCS_BY_CAT_RECORD_DATA;
inline constexpr std::size_t URCS_BY_CAT_RECORD_COUNT = 1;

inline constexpr URC URCS_BY_CAT_TTS_DATA[] = {
    URCS[82],
};
inline constexpr const URC* const URCS_BY_CAT_TTS = URCS_BY_CAT_TTS_DATA;
inline constexpr std::size_t URCS_BY_CAT_TTS_COUNT = 1;

inline constexpr URC URCS_BY_MOD_0_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_0 = URCS_BY_MOD_0_DATA;
inline constexpr std::size_t URCS_BY_MOD_0_COUNT = 95;

inline constexpr URC URCS_BY_MOD_1_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_1 = URCS_BY_MOD_1_DATA;
inline constexpr std::size_t URCS_BY_MOD_1_COUNT = 94;

inline constexpr URC URCS_BY_MOD_2_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_2 = URCS_BY_MOD_2_DATA;
inline constexpr std::size_t URCS_BY_MOD_2_COUNT = 95;

inline constexpr URC URCS_BY_MOD_3_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_3 = URCS_BY_MOD_3_DATA;
inline constexpr std::size_t URCS_BY_MOD_3_COUNT = 94;

inline constexpr URC URCS_BY_MOD_4_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_4 = URCS_BY_MOD_4_DATA;
inline constexpr std::size_t URCS_BY_MOD_4_COUNT = 95;

inline constexpr URC URCS_BY_MOD_5_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_5 = URCS_BY_MOD_5_DATA;
inline constexpr std::size_t URCS_BY_MOD_5_COUNT = 95;

inline constexpr URC URCS_BY_MOD_6_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_6 = URCS_BY_MOD_6_DATA;
inline constexpr std::size_t URCS_BY_MOD_6_COUNT = 95;

inline constexpr URC URCS_BY_MOD_7_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[91],
    URCS[92],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_7 = URCS_BY_MOD_7_DATA;
inline constexpr std::size_t URCS_BY_MOD_7_COUNT = 95;

inline constexpr URC URCS_BY_MOD_8_DATA[] = {
    URCS[0],
    URCS[1],
    URCS[2],
    URCS[3],
    URCS[4],
    URCS[5],
    URCS[6],
    URCS[7],
    URCS[8],
    URCS[9],
    URCS[10],
    URCS[11],
    URCS[12],
    URCS[13],
    URCS[14],
    URCS[15],
    URCS[16],
    URCS[17],
    URCS[18],
    URCS[19],
    URCS[20],
    URCS[21],
    URCS[22],
    URCS[23],
    URCS[24],
    URCS[25],
    URCS[26],
    URCS[27],
    URCS[28],
    URCS[29],
    URCS[30],
    URCS[31],
    URCS[32],
    URCS[33],
    URCS[34],
    URCS[35],
    URCS[36],
    URCS[37],
    URCS[38],
    URCS[39],
    URCS[40],
    URCS[41],
    URCS[42],
    URCS[43],
    URCS[44],
    URCS[45],
    URCS[46],
    URCS[47],
    URCS[48],
    URCS[49],
    URCS[50],
    URCS[51],
    URCS[52],
    URCS[53],
    URCS[54],
    URCS[55],
    URCS[56],
    URCS[57],
    URCS[58],
    URCS[59],
    URCS[60],
    URCS[61],
    URCS[62],
    URCS[63],
    URCS[64],
    URCS[65],
    URCS[66],
    URCS[67],
    URCS[68],
    URCS[69],
    URCS[70],
    URCS[71],
    URCS[72],
    URCS[73],
    URCS[74],
    URCS[75],
    URCS[76],
    URCS[77],
    URCS[78],
    URCS[79],
    URCS[80],
    URCS[81],
    URCS[82],
    URCS[83],
    URCS[84],
    URCS[85],
    URCS[86],
    URCS[87],
    URCS[88],
    URCS[89],
    URCS[90],
    URCS[93],
    URCS[94],
};
inline constexpr const URC* const URCS_BY_MOD_8 = URCS_BY_MOD_8_DATA;
inline constexpr std::size_t URCS_BY_MOD_8_COUNT = 93;

struct CatUrcView { const URC* data; std::size_t count; };
inline constexpr CatUrcView URCS_BY_CAT_TABLE[] = {
    { URCS_BY_CAT_V25TER, URCS_BY_CAT_V25TER_COUNT },
    { URCS_BY_CAT_cat_3GPP_27007, URCS_BY_CAT_cat_3GPP_27007_COUNT },
    { URCS_BY_CAT_cat_3GPP_27005, URCS_BY_CAT_cat_3GPP_27005_COUNT },
    { URCS_BY_CAT_STK, URCS_BY_CAT_STK_COUNT },
    { URCS_BY_CAT_SIMCom, URCS_BY_CAT_SIMCom_COUNT },
    { URCS_BY_CAT_GPRS, URCS_BY_CAT_GPRS_COUNT },
    { URCS_BY_CAT_TCPIP, URCS_BY_CAT_TCPIP_COUNT },
    { URCS_BY_CAT_IP, URCS_BY_CAT_IP_COUNT },
    { URCS_BY_CAT_PING, URCS_BY_CAT_PING_COUNT },
    { URCS_BY_CAT_HTTP, URCS_BY_CAT_HTTP_COUNT },
    { URCS_BY_CAT_FTP, URCS_BY_CAT_FTP_COUNT },
    { URCS_BY_CAT_GSM_Location, URCS_BY_CAT_GSM_Location_COUNT },
    { URCS_BY_CAT_Email, URCS_BY_CAT_Email_COUNT },
    { URCS_BY_CAT_MMS, URCS_BY_CAT_MMS_COUNT },
    { URCS_BY_CAT_DDET, URCS_BY_CAT_DDET_COUNT },
    { URCS_BY_CAT_RECORD, URCS_BY_CAT_RECORD_COUNT },
    { URCS_BY_CAT_TTS, URCS_BY_CAT_TTS_COUNT },
};

struct ModUrcView { const URC* data; std::size_t count; };
inline constexpr ModUrcView URCS_BY_MOD_TABLE[] = {
    { URCS_BY_MOD_0, URCS_BY_MOD_0_COUNT },
    { URCS_BY_MOD_1, URCS_BY_MOD_1_COUNT },
    { URCS_BY_MOD_2, URCS_BY_MOD_2_COUNT },
    { URCS_BY_MOD_3, URCS_BY_MOD_3_COUNT },
    { URCS_BY_MOD_4, URCS_BY_MOD_4_COUNT },
    { URCS_BY_MOD_5, URCS_BY_MOD_5_COUNT },
    { URCS_BY_MOD_6, URCS_BY_MOD_6_COUNT },
    { URCS_BY_MOD_7, URCS_BY_MOD_7_COUNT },
    { URCS_BY_MOD_8, URCS_BY_MOD_8_COUNT },
};

} // namespace sim800_at

#endif // SIM800_AT_URCS_HPP
