#ifndef SIM800_AT_VERSION_HPP
#define SIM800_AT_VERSION_HPP

// ---------------------------------------------------------------------------
// Hand-written file. NOT generated by tools/generate.py.
// tools/generate.py MUST NOT overwrite this file.
// ---------------------------------------------------------------------------

#define SIM800_AT_API_VERSION_MAJOR 0
#define SIM800_AT_API_VERSION_MINOR 1
#define SIM800_AT_API_VERSION_PATCH 0

#endif // SIM800_AT_VERSION_HPP