#!/usr/bin/env python3
"""Generate C++ headers from YAML data sources (idempotent).

Notes
-----
* ``include/sim800_at/version.hpp`` is hand-written and MUST NOT be
  generated or overwritten by this script.
* ``--with-dist`` (off by default) additionally emits JSON / CSV / Markdown
  into ``dist/``.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML is required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUT_DIR = PROJECT_ROOT / "include" / "sim800_at"
DIST_DIR = PROJECT_ROOT / "dist"

# Files this script is FORBIDDEN to write.
FORBIDDEN_OUTPUTS = {
    OUT_DIR / "version.hpp",
}

GEN_BANNER = (
    "// -----------------------------------------------------------------------\n"
    "// GENERATED FILE - DO NOT EDIT\n"
    "// Generated by tools/generate.py from data/*.yaml\n"
    "// -----------------------------------------------------------------------\n\n"
)


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data or []


def cpp_str(s):
    if s is None:
        return "nullptr"
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def ident(name: str) -> str:
    out = []
    for ch in name:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    if out and out[0].isdigit():
        out.insert(0, "cat_")
    return "".join(out)


def write_if_changed(path: Path, content: str) -> bool:
    if path in FORBIDDEN_OUTPUTS:
        raise RuntimeError(f"Refusing to write forbidden output: {path}")
    if path.is_file():
        old = path.read_text(encoding="utf-8")
        if old == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def gen_types(modules, categories):
    lines = []
    lines.append("#ifndef SIM800_AT_TYPES_HPP\n#define SIM800_AT_TYPES_HPP\n\n")
    lines.append(GEN_BANNER)
    lines.append("#include <cstdint>\n#include <cstddef>\n\n")
    lines.append("namespace sim800_at {\n\n")
    lines.append("enum class Category : std::uint8_t {\n")
    for i, c in enumerate(categories):
        lines.append(f"    {ident(c['id'])} = {i},\n")
    lines.append(f"    COUNT = {len(categories)},\n")
    lines.append("    INVALID = 0xFF\n")
    lines.append("};\n\n")
    lines.append("enum class ParamType : std::uint8_t {\n")
    lines.append("    String = 0,\n    Int = 1,\n    Bool = 2,\n    Enum = 3,\n    COUNT = 4\n")
    lines.append("};\n\n")
    lines.append("struct Parameter {\n")
    lines.append("    const char* name;\n    ParamType   type;\n    const char* values_or_range;\n")
    lines.append("};\n\n")
    lines.append("struct ATCommand {\n")
    lines.append("    const char*        name;\n    Category           category;\n")
    lines.append("    const char*        description;\n    const Parameter*   parameters;\n")
    lines.append("    std::size_t        parameter_count;\n    const char* const* responses;\n")
    lines.append("    std::size_t        response_count;\n    const char* const* related_urcs;\n")
    lines.append("    std::size_t        related_urc_count;\n    const bool*        module_support;\n")
    lines.append("    const char*        manual_ref;\n};\n\n")
    lines.append("struct URC {\n")
    lines.append("    const char*        name;\n    Category           category;\n")
    lines.append("    const char*        description;\n    const char* const* payload;\n")
    lines.append("    std::size_t        payload_count;\n    const char* const* enabled_by;\n")
    lines.append("    std::size_t        enabled_by_count;\n    const bool*        module_support;\n")
    lines.append("    const char*        manual_ref;\n};\n\n")
    lines.append("} // namespace sim800_at\n\n#endif // SIM800_AT_TYPES_HPP\n")
    return "".join(lines)


def _support_array(modules, rec):
    n = len(modules)
    mod_by_name = {m["name"]: i for i, m in enumerate(modules)}
    arr = [False] * n
    if rec.get("removed_after"):
        return arr
    if rec.get("all_modules"):
        return [True] * n
    for name in rec.get("supported_on") or []:
        arr[mod_by_name[name]] = True
    return arr


def gen_commands(modules, categories, commands):
    n_mod = len(modules)
    lines = []
    lines.append("#ifndef SIM800_AT_COMMANDS_HPP\n#define SIM800_AT_COMMANDS_HPP\n\n")
    lines.append(GEN_BANNER)
    lines.append('#include "at_types.hpp"\n')
    lines.append("#include <cstddef>\n\n")
    lines.append("namespace sim800_at {\n\n")

    for i, c in enumerate(commands):
        arr = _support_array(modules, c)
        vals = ", ".join("true" if b else "false" for b in arr)
        lines.append(f"inline constexpr bool CMDS_SUPPORT_{i}[] = {{ {vals} }};\n")
    lines.append("\n")

    for i, c in enumerate(commands):
        params = c.get("parameters") or []
        if params:
            lines.append(f"inline constexpr Parameter CMDS_PARAMS_{i}[] = {{\n")
            for p in params:
                ptype = {"string": "String", "int": "Int",
                         "bool": "Bool", "enum": "Enum"}[p["type"]]
                lines.append(
                    f"    {{ {cpp_str(p['name'])}, ParamType::{ptype}, "
                    f"{cpp_str(p.get('values_or_range',''))} }},\n"
                )
            lines.append("};\n")
        else:
            lines.append(f"inline constexpr Parameter* CMDS_PARAMS_{i} = nullptr;\n")

    for i, c in enumerate(commands):
        resps = c.get("responses") or []
        if resps:
            lines.append(f"inline constexpr const char* CMDS_RESP_{i}[] = {{\n")
            for r in resps:
                lines.append(f"    {cpp_str(r)},\n")
            lines.append("};\n")
        else:
            lines.append(f"inline constexpr const char** CMDS_RESP_{i} = nullptr;\n")

    for i, c in enumerate(commands):
        urcs = c.get("related_urcs") or []
        if urcs:
            lines.append(f"inline constexpr const char* CMDS_RURC_{i}[] = {{\n")
            for u in urcs:
                lines.append(f"    {cpp_str(u)},\n")
            lines.append("};\n")
        else:
            lines.append(f"inline constexpr const char** CMDS_RURC_{i} = nullptr;\n")

    lines.append("\n")
    lines.append("inline constexpr ATCommand AT_COMMANDS[] = {\n")
    for i, c in enumerate(commands):
        params = c.get("parameters") or []
        resps = c.get("responses") or []
        urcs = c.get("related_urcs") or []
        lines.append("    {\n")
        lines.append(f"        {cpp_str(c['name'])},\n")
        lines.append(f"        Category::{ident(c['category'])},\n")
        lines.append(f"        {cpp_str(c['description'])},\n")
        lines.append(f"        CMDS_PARAMS_{i}, {len(params)},\n")
        lines.append(f"        CMDS_RESP_{i}, {len(resps)},\n")
        lines.append(f"        CMDS_RURC_{i}, {len(urcs)},\n")
        lines.append(f"        CMDS_SUPPORT_{i},\n")
        lines.append(f"        {cpp_str(c['manual_ref'])}\n")
        lines.append("    },\n")
    lines.append("};\n\n")
    lines.append(f"inline constexpr std::size_t AT_COMMAND_COUNT = {len(commands)};\n\n")

    for cat in categories:
        cat_id = cat["id"]
        id_safe = ident(cat_id)
        filtered = [j for j, c in enumerate(commands) if c["category"] == cat_id]
        if filtered:
            lines.append(f"inline constexpr ATCommand CMDS_BY_CAT_{id_safe}_DATA[] = {{\n")
            for j in filtered:
                lines.append(f"    AT_COMMANDS[{j}],\n")
            lines.append("};\n")
            lines.append(f"inline constexpr const ATCommand* const CMDS_BY_CAT_{id_safe} = CMDS_BY_CAT_{id_safe}_DATA;\n")
            lines.append(f"inline constexpr std::size_t CMDS_BY_CAT_{id_safe}_COUNT = {len(filtered)};\n\n")
        else:
            lines.append(f"inline constexpr const ATCommand* const CMDS_BY_CAT_{id_safe} = nullptr;\n")
            lines.append(f"inline constexpr std::size_t CMDS_BY_CAT_{id_safe}_COUNT = 0;\n\n")

    for m_idx in range(n_mod):
        filtered = [j for j, c in enumerate(commands) if _support_array(modules, c)[m_idx]]
        if filtered:
            lines.append(f"inline constexpr ATCommand CMDS_BY_MOD_{m_idx}_DATA[] = {{\n")
            for j in filtered:
                lines.append(f"    AT_COMMANDS[{j}],\n")
            lines.append("};\n")
            lines.append(f"inline constexpr const ATCommand* const CMDS_BY_MOD_{m_idx} = CMDS_BY_MOD_{m_idx}_DATA;\n")
            lines.append(f"inline constexpr std::size_t CMDS_BY_MOD_{m_idx}_COUNT = {len(filtered)};\n\n")
        else:
            lines.append(f"inline constexpr const ATCommand* const CMDS_BY_MOD_{m_idx} = nullptr;\n")
            lines.append(f"inline constexpr std::size_t CMDS_BY_MOD_{m_idx}_COUNT = 0;\n\n")

    lines.append("struct CatCmdView { const ATCommand* data; std::size_t count; };\n")
    lines.append("inline constexpr CatCmdView CMDS_BY_CAT_TABLE[] = {\n")
    for cat in categories:
        id_safe = ident(cat["id"])
        lines.append(f"    {{ CMDS_BY_CAT_{id_safe}, CMDS_BY_CAT_{id_safe}_COUNT }},\n")
    lines.append("};\n\n")

    lines.append("struct ModCmdView { const ATCommand* data; std::size_t count; };\n")
    lines.append("inline constexpr ModCmdView CMDS_BY_MOD_TABLE[] = {\n")
    for m_idx in range(n_mod):
        lines.append(f"    {{ CMDS_BY_MOD_{m_idx}, CMDS_BY_MOD_{m_idx}_COUNT }},\n")
    lines.append("};\n\n")

    lines.append("} // namespace sim800_at\n\n#endif // SIM800_AT_COMMANDS_HPP\n")
    return "".join(lines)


def gen_urcs(modules, categories, urcs):
    n_mod = len(modules)
    lines = []
    lines.append("#ifndef SIM800_AT_URCS_HPP\n#define SIM800_AT_URCS_HPP\n\n")
    lines.append(GEN_BANNER)
    lines.append('#include "at_types.hpp"\n')
    lines.append("#include <cstddef>\n\n")
    lines.append("namespace sim800_at {\n\n")

    for i, u in enumerate(urcs):
        arr = _support_array(modules, u)
        vals = ", ".join("true" if b else "false" for b in arr)
        lines.append(f"inline constexpr bool URCS_SUPPORT_{i}[] = {{ {vals} }};\n")
    lines.append("\n")

    for i, u in enumerate(urcs):
        payload = u.get("payload") or []
        if payload:
            lines.append(f"inline constexpr const char* URCS_PAYLOAD_{i}[] = {{\n")
            for p in payload:
                lines.append(f"    {cpp_str(p)},\n")
            lines.append("};\n")
        else:
            lines.append(f"inline constexpr const char** URCS_PAYLOAD_{i} = nullptr;\n")

    for i, u in enumerate(urcs):
        eb = u.get("enabled_by") or []
        if eb:
            lines.append(f"inline constexpr const char* URCS_EB_{i}[] = {{\n")
            for e in eb:
                lines.append(f"    {cpp_str(e)},\n")
            lines.append("};\n")
        else:
            lines.append(f"inline constexpr const char** URCS_EB_{i} = nullptr;\n")

    lines.append("\n")
    lines.append("inline constexpr URC URCS[] = {\n")
    for i, u in enumerate(urcs):
        payload = u.get("payload") or []
        eb = u.get("enabled_by") or []
        lines.append("    {\n")
        lines.append(f"        {cpp_str(u['name'])},\n")
        lines.append(f"        Category::{ident(u['category'])},\n")
        lines.append(f"        {cpp_str(u['description'])},\n")
        lines.append(f"        URCS_PAYLOAD_{i}, {len(payload)},\n")
        lines.append(f"        URCS_EB_{i}, {len(eb)},\n")
        lines.append(f"        URCS_SUPPORT_{i},\n")
        lines.append(f"        {cpp_str(u['manual_ref'])}\n")
        lines.append("    },\n")
    lines.append("};\n\n")
    lines.append(f"inline constexpr std::size_t URC_COUNT = {len(urcs)};\n\n")

    for cat in categories:
        cat_id = cat["id"]
        id_safe = ident(cat_id)
        filtered = [j for j, u in enumerate(urcs) if u["category"] == cat_id]
        if filtered:
            lines.append(f"inline constexpr URC URCS_BY_CAT_{id_safe}_DATA[] = {{\n")
            for j in filtered:
                lines.append(f"    URCS[{j}],\n")
            lines.append("};\n")
            lines.append(f"inline constexpr const URC* const URCS_BY_CAT_{id_safe} = URCS_BY_CAT_{id_safe}_DATA;\n")
            lines.append(f"inline constexpr std::size_t URCS_BY_CAT_{id_safe}_COUNT = {len(filtered)};\n\n")
        else:
            lines.append(f"inline constexpr const URC* const URCS_BY_CAT_{id_safe} = nullptr;\n")
            lines.append(f"inline constexpr std::size_t URCS_BY_CAT_{id_safe}_COUNT = 0;\n\n")

    for m_idx in range(n_mod):
        filtered = [j for j, u in enumerate(urcs) if _support_array(modules, u)[m_idx]]
        if filtered:
            lines.append(f"inline constexpr URC URCS_BY_MOD_{m_idx}_DATA[] = {{\n")
            for j in filtered:
                lines.append(f"    URCS[{j}],\n")
            lines.append("};\n")
            lines.append(f"inline constexpr const URC* const URCS_BY_MOD_{m_idx} = URCS_BY_MOD_{m_idx}_DATA;\n")
            lines.append(f"inline constexpr std::size_t URCS_BY_MOD_{m_idx}_COUNT = {len(filtered)};\n\n")
        else:
            lines.append(f"inline constexpr const URC* const URCS_BY_MOD_{m_idx} = nullptr;\n")
            lines.append(f"inline constexpr std::size_t URCS_BY_MOD_{m_idx}_COUNT = 0;\n\n")

    lines.append("struct CatUrcView { const URC* data; std::size_t count; };\n")
    lines.append("inline constexpr CatUrcView URCS_BY_CAT_TABLE[] = {\n")
    for cat in categories:
        id_safe = ident(cat["id"])
        lines.append(f"    {{ URCS_BY_CAT_{id_safe}, URCS_BY_CAT_{id_safe}_COUNT }},\n")
    lines.append("};\n\n")

    lines.append("struct ModUrcView { const URC* data; std::size_t count; };\n")
    lines.append("inline constexpr ModUrcView URCS_BY_MOD_TABLE[] = {\n")
    for m_idx in range(n_mod):
        lines.append(f"    {{ URCS_BY_MOD_{m_idx}, URCS_BY_MOD_{m_idx}_COUNT }},\n")
    lines.append("};\n\n")

    lines.append("} // namespace sim800_at\n\n#endif // SIM800_AT_URCS_HPP\n")
    return "".join(lines)


def gen_api(modules, categories, commands, urcs):
    n = len(modules)
    lines = []
    lines.append("#ifndef SIM800_AT_API_HPP\n#define SIM800_AT_API_HPP\n\n")
    lines.append(GEN_BANNER)
    lines.append('#include "at_types.hpp"\n')
    lines.append('#include "at_commands.hpp"\n')
    lines.append('#include "urcs.hpp"\n')
    lines.append("#include <cstddef>\n#include <cstdint>\n\n")
    lines.append("namespace sim800_at {\n\n")
    lines.append("inline constexpr const char* MODULE_NAMES[] = {\n")
    for m in modules:
        lines.append(f"    {cpp_str(m['name'])},\n")
    lines.append("};\n\n")
    lines.append("inline constexpr const char* CATEGORY_LABELS[] = {\n")
    for c in categories:
        lines.append(f"    {cpp_str(c['label'])},\n")
    lines.append("};\n\n")
    lines.append("inline constexpr const char* CATEGORY_IDS[] = {\n")
    for c in categories:
        lines.append(f"    {cpp_str(c['id'])},\n")
    lines.append("};\n\n")
    lines.append(f"""inline constexpr std::size_t MODULE_COUNT = {n};
inline constexpr std::size_t CATEGORY_COUNT = {len(categories)};

inline char lower_ascii(char c) noexcept {{
    return (c >= 'A' && c <= 'Z') ? static_cast<char>(c + 32) : c;
}}

inline bool str_equal_cs(const char* a, const char* b) noexcept {{
    if (a == nullptr || b == nullptr) return false;
    while (*a != '\\0' && *b != '\\0') {{
        if (*a != *b) return false;
        ++a; ++b;
    }}
    return *a == *b;
}}

inline bool str_equal_ci(const char* a, const char* b) noexcept {{
    if (a == nullptr || b == nullptr) return false;
    while (*a != '\\0' && *b != '\\0') {{
        if (lower_ascii(*a) != lower_ascii(*b)) return false;
        ++a; ++b;
    }}
    return *a == *b;
}}

inline std::size_t total_modules() noexcept {{ return MODULE_COUNT; }}
inline std::size_t total_categories() noexcept {{ return CATEGORY_COUNT; }}
inline std::size_t total_commands() noexcept {{ return AT_COMMAND_COUNT; }}
inline std::size_t total_urcs() noexcept {{ return URC_COUNT; }}

inline const char* module_name_at(std::size_t index) noexcept {{
    if (index >= MODULE_COUNT) return nullptr;
    return MODULE_NAMES[index];
}}

inline int module_index(const char* name) noexcept {{
    if (name == nullptr) return -1;
    for (std::size_t i = 0; i < MODULE_COUNT; ++i) {{
        if (str_equal_cs(MODULE_NAMES[i], name)) return static_cast<int>(i);
    }}
    return -1;
}}

inline Category category_from_id(const char* id) noexcept {{
    if (id == nullptr) return Category::INVALID;
    for (std::size_t i = 0; i < CATEGORY_COUNT; ++i) {{
        if (str_equal_ci(CATEGORY_IDS[i], id)) {{
            return static_cast<Category>(i);
        }}
    }}
    return Category::INVALID;
}}

inline const char* category_name(Category c) noexcept {{
    if (c == Category::INVALID) return "<invalid>";
    if (c == Category::COUNT) return "<count>";
    std::size_t idx = static_cast<std::size_t>(c);
    if (idx >= CATEGORY_COUNT) return "<invalid>";
    return CATEGORY_LABELS[idx];
}}

inline const ATCommand* find_command(const char* name) noexcept {{
    if (name == nullptr) return nullptr;
    for (std::size_t i = 0; i < AT_COMMAND_COUNT; ++i) {{
        if (str_equal_ci(AT_COMMANDS[i].name, name)) return &AT_COMMANDS[i];
    }}
    return nullptr;
}}

inline const URC* find_urc(const char* name) noexcept {{
    if (name == nullptr) return nullptr;
    for (std::size_t i = 0; i < URC_COUNT; ++i) {{
        if (str_equal_cs(URCS[i].name, name)) return &URCS[i];
    }}
    return nullptr;
}}

inline bool is_command_supported(const ATCommand* cmd,
                                 const char* module_name) noexcept {{
    if (cmd == nullptr || module_name == nullptr) return false;
    int idx = module_index(module_name);
    if (idx < 0) return false;
    return cmd->module_support[idx];
}}

inline bool is_urc_supported(const URC* urc,
                             const char* module_name) noexcept {{
    if (urc == nullptr || module_name == nullptr) return false;
    int idx = module_index(module_name);
    if (idx < 0) return false;
    return urc->module_support[idx];
}}

inline const ATCommand* commands_by_category(Category c,
                                             std::size_t& count) noexcept {{
    count = 0;
    if (c == Category::INVALID || c == Category::COUNT) return nullptr;
    std::size_t idx = static_cast<std::size_t>(c);
    if (idx >= CATEGORY_COUNT) return nullptr;
    count = CMDS_BY_CAT_TABLE[idx].count;
    return CMDS_BY_CAT_TABLE[idx].data;
}}

inline const URC* urcs_by_category(Category c,
                                   std::size_t& count) noexcept {{
    count = 0;
    if (c == Category::INVALID || c == Category::COUNT) return nullptr;
    std::size_t idx = static_cast<std::size_t>(c);
    if (idx >= CATEGORY_COUNT) return nullptr;
    count = URCS_BY_CAT_TABLE[idx].count;
    return URCS_BY_CAT_TABLE[idx].data;
}}

inline const ATCommand* commands_for_module(const char* module_name,
                                            std::size_t& count) noexcept {{
    count = 0;
    if (module_name == nullptr) return nullptr;
    int idx = module_index(module_name);
    if (idx < 0) return nullptr;
    count = CMDS_BY_MOD_TABLE[idx].count;
    return CMDS_BY_MOD_TABLE[idx].data;
}}

inline const URC* urcs_for_module(const char* module_name,
                                  std::size_t& count) noexcept {{
    count = 0;
    if (module_name == nullptr) return nullptr;
    int idx = module_index(module_name);
    if (idx < 0) return nullptr;
    count = URCS_BY_MOD_TABLE[idx].count;
    return URCS_BY_MOD_TABLE[idx].data;
}}

}} // namespace sim800_at

#endif // SIM800_AT_API_HPP
""")
    return "".join(lines)


# --------------------------------------------------------------------------
# Optional dist/ outputs (JSON / CSV / Markdown). Off by default.
# --------------------------------------------------------------------------
def _cmd_to_dict(c):
    return {
        "name": c["name"],
        "category": c["category"],
        "description": c["description"],
        "manual_ref": c["manual_ref"],
        "source_ref": c.get("source_ref", ""),
        "parameters": c.get("parameters") or [],
        "responses": c.get("responses") or [],
        "related_urcs": c.get("related_urcs") or [],
        "all_modules": bool(c.get("all_modules")),
        "supported_on": c.get("supported_on") or [],
        "removed_after": c.get("removed_after"),
        "version_notes": c.get("version_notes"),
    }


def _urc_to_dict(u):
    return {
        "name": u["name"],
        "category": u["category"],
        "description": u["description"],
        "manual_ref": u["manual_ref"],
        "source_ref": u.get("source_ref", ""),
        "payload": u.get("payload") or [],
        "enabled_by": u.get("enabled_by") or [],
        "all_modules": bool(u.get("all_modules")),
        "supported_on": u.get("supported_on") or [],
        "removed_after": u.get("removed_after"),
        "version_notes": u.get("version_notes"),
    }


def gen_dist(modules, categories, commands, urcs, data_version, manuals):
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    meta = {
        "data_version": data_version,
        "manuals": manuals,
        "category_count": len(categories),
        "module_count": len(modules),
    }

    # JSON
    with (DIST_DIR / "at_commands.json").open("w", encoding="utf-8", newline="\n") as f:
        json.dump({"meta": meta, "commands": [_cmd_to_dict(c) for c in commands]},
                  f, indent=2, ensure_ascii=False)
        f.write("\n")
    with (DIST_DIR / "urcs.json").open("w", encoding="utf-8", newline="\n") as f:
        json.dump({"meta": meta, "urcs": [_urc_to_dict(u) for u in urcs]},
                  f, indent=2, ensure_ascii=False)
        f.write("\n")

    # CSV
    def _write_csv(path, rows, header):
        with path.open("w", encoding="utf-8", newline="") as f:
            w = csv.writer(f)
            w.writerow(header)
            for row in rows:
                w.writerow(row)

    cmd_header = ["Name", "Category", "Description", "Parameters",
                  "Responses", "Related URCs", "Supported Modules", "Manual Ref"]
    cmd_rows = []
    for c in commands:
        params = "; ".join(
            f"{p['name']}:{p['type']}:{p.get('values_or_range','')}"
            for p in (c.get("parameters") or [])
        )
        resps = " | ".join(c.get("responses") or [])
        rurcs = ", ".join(c.get("related_urcs") or [])
        if c.get("all_modules"):
            mods = "ALL"
        elif c.get("removed_after"):
            mods = f"REMOVED_AFTER={c['removed_after']}"
        else:
            mods = ", ".join(c.get("supported_on") or [])
        cmd_rows.append([c["name"], c["category"], c["description"],
                         params, resps, rurcs, mods, c["manual_ref"]])
    _write_csv(DIST_DIR / "at_commands.csv", cmd_rows, cmd_header)

    urc_header = ["Name", "Category", "Description", "Payload",
                  "Enabled By", "Supported Modules", "Manual Ref"]
    urc_rows = []
    for u in urcs:
        payload = " | ".join(u.get("payload") or [])
        eb = ", ".join(u.get("enabled_by") or [])
        if u.get("all_modules"):
            mods = "ALL"
        elif u.get("removed_after"):
            mods = f"REMOVED_AFTER={u['removed_after']}"
        else:
            mods = ", ".join(u.get("supported_on") or [])
        urc_rows.append([u["name"], u["category"], u["description"],
                         payload, eb, mods, u["manual_ref"]])
    _write_csv(DIST_DIR / "urcs.csv", urc_rows, urc_header)

    # Markdown
    def _md_escape(s):
        return str(s).replace("|", "\\|").replace("\n", " ")

    with (DIST_DIR / "at_commands.md").open("w", encoding="utf-8", newline="\n") as f:
        f.write("# AT Commands\n\n")
        f.write(f"Data version: {data_version}  \n")
        f.write(f"Manuals: {manuals}  \n")
        f.write(f"Total: {len(commands)}\n\n")
        f.write("| Name | Category | Description | Manual Ref |\n")
        f.write("|------|----------|-------------|------------|\n")
        for c in commands:
            f.write(f"| `{_md_escape(c['name'])}` | {_md_escape(c['category'])} | "
                    f"{_md_escape(c['description'])} | {_md_escape(c['manual_ref'])} |\n")

    with (DIST_DIR / "urcs.md").open("w", encoding="utf-8", newline="\n") as f:
        f.write("# URCs\n\n")
        f.write(f"Data version: {data_version}  \n")
        f.write(f"Manuals: {manuals}  \n")
        f.write(f"Total: {len(urcs)}\n\n")
        f.write("| Name | Category | Description | Enabled By | Manual Ref |\n")
        f.write("|------|----------|-------------|------------|------------|\n")
        for u in urcs:
            eb = ", ".join(u.get("enabled_by") or []) or "-"
            f.write(f"| `{_md_escape(u['name'])}` | {_md_escape(u['category'])} | "
                    f"{_md_escape(u['description'])} | {_md_escape(eb)} | "
                    f"{_md_escape(u['manual_ref'])} |\n")


def read_version():
    p = DATA_DIR / "VERSION"
    return p.read_text(encoding="utf-8").strip() if p.is_file() else "1.0.0"


def read_manuals():
    p = DATA_DIR / "MANUALS"
    return p.read_text(encoding="utf-8").strip() if p.is_file() else ""


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate SIM800 AT database artifacts.")
    ap.add_argument("--with-dist", action="store_true",
                    help="Also emit dist/ JSON, CSV and Markdown (off by default).")
    args = ap.parse_args()

    modules = load_yaml(DATA_DIR / "modules.yaml")
    categories = load_yaml(DATA_DIR / "categories.yaml")
    commands = load_yaml(DATA_DIR / "at_commands.yaml")
    urcs = load_yaml(DATA_DIR / "urcs.yaml")

    if len(categories) >= 0xFF:
        print("Too many categories; max 254 allowed.", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    files = {
        "at_types.hpp": gen_types(modules, categories),
        "at_commands.hpp": gen_commands(modules, categories, commands),
        "urcs.hpp": gen_urcs(modules, categories, urcs),
        "at_api.hpp": gen_api(modules, categories, commands, urcs),
    }

    changed = 0
    for name, content in files.items():
        if write_if_changed(OUT_DIR / name, content):
            print(f"  [write] {OUT_DIR / name}")
            changed += 1
        else:
            print(f"  [ok]    {OUT_DIR / name} (unchanged)")

    if args.with_dist:
        gen_dist(modules, categories, commands, urcs,
                 read_version(), read_manuals())
        print(f"  [dist]  {DIST_DIR}")

    print(f"generate.py: {changed} file(s) written.")
    return 0


if __name__ == "__main__":
    sys.exit(main())